export const NEARBY_REQUEST_LOCATION = "NEARBY_REQUEST_LOCATION";
export const NEARBY_LOCATION_SUCCESS = "NEARBY_LOCATION_SUCCESS";
export const NEARBY_LOCATION_DENIED = "NEARBY_LOCATION_DENIED";
export const NEARBY_FETCH_SUCCESS = "NEARBY_FETCH_SUCCESS";
export const NEARBY_FETCH_ERROR = "NEARBY_FETCH_ERROR";
export const NEARBY_RESET = "NEARBY_RESET";
