export const QUEUE_ADD_ACTION = "QUEUE_ADD_ACTION";
export const QUEUE_REMOVE_ACTION = "QUEUE_REMOVE_ACTION";
export const QUEUE_CLEAR = "QUEUE_CLEAR";
export const QUEUE_SYNC_START = "QUEUE_SYNC_START";
export const QUEUE_SYNC_SUCCESS = "QUEUE_SYNC_SUCCESS";
export const QUEUE_SYNC_ERROR = "QUEUE_SYNC_ERROR";
export const QUEUE_ITEM_FAILED = "QUEUE_ITEM_FAILED";